---
title: "Project 6: Shiny Project"
output:
  html_document:
    pandoc_args: [
      "+RTS", "-K64m",
      "-RTS"
    ]
---
For analysis we are using a database of medical data containing information on the cost of some common medical procedures. 

###Reproducing Our Work:
1. Create a GitHub repository for the project.
2. Create the folders for project.
3. Find a csv file for statistical comparisons. Our CSV file was found on data.gov. Link: https://data.cms.gov/Medicare/Inpatient-Prospective-Payment-System-IPPS-Provider/97k6-zzx3
4. Import CSV into SQL Developer.
5. Visualize data in R using code included below.
6. Package and publish app to shiny free application.

###Required Packages
```{r, echo=TRUE}
source("../require.R",  echo = TRUE)
```

###Plot #1: Crosstab w/ KPI
Our crosstab examines common medical procedures against the state they're performed in. Data analyzed is the ratio of total payments to the procedure over the total US dollar amount billed to the patient for the procedure. As shown by the table, hospitals are rarely receiving as little as half of their total charges, and most frequently are receving between 20%-40% of their charges. Some states have very low payment ratios across all types of medical procedures, such as California.

Questions Raised by Data:
1. Why do hospitals charge so much in the first place? Is it because they know they will not receive the full payment amount?
2. How are people getting away with not paying medical bills in full?

###Reproducing the work:
The crosstab was originally produced in tableau and replicated in R. See the following repository for that work: https://github.com/garnerv/DV_TProject1. In this project, the shiny package was used along side the appropriate R code in the 'server.R' and 'require.R' files in order to create the shiny reactive application. 

The crosstab is first loaded into an object with the server call that pulls in the appropriate data frame in line 13 of 'server.r'. KPI low max and KPI medium max are then created as slider objects in line 16 and 17 of 'server.r'. In line 22, the output is rendered into output$distPlot1. Layers for various parts of the plot are applied using the ggplot2 package. 'Plot' in line 63 calls the plot. Line 66 is an observing function to count the number of clicks the user initiates.

Note about the plot:
The KPI is initialized at the following values: The max low KPI is set at .2, while the max medium KPI is set at .4, and anything higher is coded as "high". You may adjust the values using the shiny sliders.
See the application and this plot under 'crosstab' here:

https://garnervincent.shinyapps.io/DV_SProject


###Plot #2: Bar Chart with Reference Line
This bar chart compares average out of pocket and medicare payments of different medical precedures.  I added a calculated field of average difference between total payments and medicare payments to see how much on average comes directly out of pocket.  I then added a refrence band to show you exactly where that average difference comes from.  We can see Intracranial Hemorrhage procedures are by far the most expensive but for out of pocket payments its not quite as expensive as Extracranial Procedures. 

Questions Raised by Data:
1. Why are out of pocket expenses for Extracranial Procedures just as expensive as Intracranial Hemorrhage when the total payments reflect differently?
2. Why is the cost so high if so much of the cost is covered from the beginning?

###Reproducing the work:
The barchart was originally produced in tableau and replicated in R. See the following repository for that work: https://github.com/garnerv/DV_TProject1. In this project, the shiny package was used along side the appropriate R code in the 'server.R' and 'require.R' files in order to create the shiny reactive application. 

First, the dataframe is created with a SQL call to the server to pull out the medical data. Piping using R code is then done to mutate the data and produce a more interesting plot. DF4 is created as an object using an inner join to the prior created data frames. Finally, GGplot is used with the render plot function to create the plot. The object is reactive so that when the button, 'Click me' is clicked as designated as click1 in the ui.r file.

###Plot #3: ScatterPlot
This scatterplot compares the percentile of the average difference (average difference between average total payments and average medicare payments, so out of pocket payments) and total discharges.  There is an interesting set of lines visible from the plot.  They start nearly at the 0th percentile and run to about the 60th percentile.  I honestly don't understand what they could mean.  But the plot also shows an interesting drop just before the 70th percentile and from after that looks just scattered.

Questions Raised by Data:
1. What is with those lines?
2. Why is there the drop off in the percentiles?

###Reproducing the work:
The scatterplot was originally produced in tableau and replicated in R. See the following repository for that work: https://github.com/garnerv/DV_TProject1. In this project, the shiny package was used along side the appropriate R code in the 'server.R' and 'require.R' files in order to create the shiny reactive application. 

First, a dataframe is created using a SQL call to the server to pull the medical data out of SQL developer. DFS2 is created as a reactive object so that when the button click button is clicked, the graph is created. The dfs2 object is called in the ggplot function because it contains the data.
